import { Inter } from "next/font/google";
import AuthProvider from "./components/SessionProvider";
import "./styles/index.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Procyon Archive",
  description: "Generated by create next app",
  icons: {
		icon: "/favicon.png",
	},
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="google" content="notranslate" />
      </head>
      <body className={inter.className}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}